version: '3'

services: 
  order_db:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    expose: 
      - "3306"
    volumes:
      - ./database/order:/docker-entrypoint-initdb.d
    environment: 
      - "MYSQL_ROOT_PASSWORD=passw0rd"

  product_db:
    image: mongo:4.2
    ports:
      - "27017:27017"
    expose: 
      - "27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=passw0rd"
      - "MONGO_DATABASE=product"
    volumes:
      - ./database/product:/docker-entrypoint-initdb.d
  product_mongo_express:
    image: mongo-express:0.49
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=passw0rd"
      - "ME_CONFIG_MONGODB_SERVER=product_db"
    external_links:
      - product_db
    depends_on: 
      - product_db


  order:
    build: dockerfiles/order
    environment: 
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./services/services/order:/home/node/src
    expose: 
      - "3001"
    ports:
      - "3001:3001"
    command: "npm start"
    external_links:
      - order_db
    depends_on: 
      - order_db

  product:
    build: dockerfiles/product
    environment: 
      - NODE_ENV=development
      - PORT=3002
    volumes:
      - ./services/services/product:/home/node/src
    expose: 
      - "3002"
    ports:
      - "3002:3002"
    command: "npm start"
    external_links:
      - product_db
    depends_on: 
      - product_db

  user:
    build: dockerfiles/user
    environment: 
      - NODE_ENV=development
      - PORT=3003
    volumes:
      - ./services/services/user:/home/node/src
    expose: 
      - "3003"
    ports:
      - "3003:3003"
    command: "npm start"

  picture:
    build: dockerfiles/picture
    environment: 
      - NODE_ENV=development
      - PORT=3004
    volumes:
      - ./services/services/picture:/home/node/src
    expose: 
      - "3004"
    ports:
      - "3004:3004"
    command: "npm start"


  admin:
    build: dockerfiles/admin
    environment: 
      - NODE_ENV=development
      - PORT=3010
    volumes:
      - ./services/web/admin:/home/node/src
    expose: 
      - "3010"
    ports:
      - "3010:3010"
    command: "npm start"

  shop:
    build: dockerfiles/shop
    environment: 
      - NODE_ENV=development
      - PORT=3011
    volumes:
      - ./services/web/shop:/home/node/src
    expose: 
      - "3011"
    ports:
      - "3011:3011"
    command: "npm start"

