version: '3'
services:
  admin:
    build: dockerfiles/admin
    environment:
      - NODE_ENV=development
      - PORT=3010
    volumes:
      - ./services/web/admin:/home/node/src
    expose:
      - "3010"
    ports:
      - "3010:3010"
    command: "npm start"
