version: '3'
services: 
  user_mongo_express:
    image: mongo-express:0.49
    ports:
      - "8082:8081"
    expose:
      - "8081"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=passw0rd"
      - "ME_CONFIG_MONGODB_SERVER=user_db"
    external_links:
      - user_db
    depends_on: 
      - user_db
