version: '3'
services: 
  user_db:
    image: mariadb:10.3
    ports:
      - "3307:3306"
    expose: 
      - "3306"
    volumes:
      - ./database/user:/docker-entrypoint-initdb.d
      - user_db_data:/var/lib/mysql
    environment: 
      - "MYSQL_ROOT_PASSWORD=passw0rd"
volumes:
  user_db_data: